cabal-version:      3.14
name:               wasmdemo
version:            0.1.0.0
-- synopsis:
-- description:
license:            MIT
license-file:       LICENSE
author:             Frank Staals
maintainer:         frank@fstaals.net
-- copyright:
category:           Web
build-type:         Simple
extra-doc-files:    CHANGELOG.md
-- extra-source-files:

common warnings
    ghc-options: -Wall -lwasi-emulated-getpid

    build-depends:
        base               >=4.20.0.0  && < 5
      , hexpat             >= 0.20.13  && < 0.21
      , bytestring         >= 0.12     && < 0.13
      , text               >= 2.1      && < 2.2
      , effectful          >= 2.5.1    && < 2.6
      , effectful-core     >= 2.5.1    && < 2.6
      , containers         >= 0.7      && < 0.9
      , dependent-map      >= 0.4      && < 0.5
      , some               >= 1.0.6    && < 1.1
      , constraints-extras >= 0.4.0.2  && < 0.5
      , dependent-sum      >= 0.7.2.0  && < 0.8
      , ghc-experimental   >= 0.1

         -- >= 9.1201   && < 9.14

    default-language: GHC2024
    default-extensions:
        DataKinds
      , TypeFamilies
      , GADTs
      , KindSignatures
      , ScopedTypeVariables
      , DerivingStrategies
      , DerivingVia
      , GeneralizedNewtypeDeriving
      , DeriveGeneric
      , DeriveFunctor
      , PatternSynonyms
      , TupleSections
      , LambdaCase
      , ViewPatterns
      , FunctionalDependencies
      , PartialTypeSignatures
      , QuantifiedConstraints


-- library
--     import: warnings
--     hs-source-dirs: src
--     exposed-modules:
       -- EffWeb.Html.Event
       -- EffWeb.Html.Element
       -- EffWeb.Html.Attribute

executable wasmdemo
    import:           warnings
    main-is:          Main.hs
    -- other-modules:
    -- other-extensions:
    hs-source-dirs:   app


executable wasmdemo-web
    import:           warnings
    main-is:          Web.hs
    ghc-options: -no-hs-main -optl-mexec-model=reactor -optl-Wl,--export=hs_start

    other-modules:
       EffWeb.Html.Event
       EffWeb.Html.Element
       EffWeb.Html.Attribute

       EffWeb.DOM.FFI
       EffWeb.DOM.FFI.Types

        -- Attributes
        -- HtmlElement
        -- HtmlEvent
        -- FFI
        -- FFI.Types
    -- other-extensions:

    hs-source-dirs:   app
