module HtmlEvent where

data EventAttr = OnAbort
               | OnAutocomplete
               | OnAutocompleteerror
               | OnBlur
               | OnCancel
               | OnCanplay
               | OnCanplaythrough
               | OnChange
               | OnClick
               | OnClose
               | OnContextmenu
               | OnCuechange
               | OnDblclick
               | OnDrag
               | OnDragend
               | OnDragenter
               | OnDragleave
               | OnDragover
               | OnDragstart
               | OnDrop
               | OnDurationchange
               | OnEmptied
               | OnEnded
               | OnError
               | OnFocus
               | OnInput
               | OnInvalid
               | OnKeydown
               | OnKeypress
               | OnKeyup
               | OnLoad
               | OnLoadeddata
               | OnLoadedmetadata
               | OnLoadstart
               | OnMousedown
               | OnMouseenter
               | OnMouseleave
               | OnMousemove
               | OnMouseout
               | OnMouseover
               | OnMouseup
               | OnMousewheel
               | OnPause
               | OnPlay
               | OnPlaying
               | OnProgress
               | OnRatechange
               | OnReset
               | OnResize
               | OnScroll
               | OnSeeked
               | OnSeeking
               | OnSelect
               | OnShow
               | OnSort
               | OnStalled
               | OnSubmit
               | OnSuspend
               | OnTimeupdate
               | OnToggle
               | OnVolumechange
               | OnWaiting
               deriving (Show,Eq,Ord,Enum)
